[package]
name = "del"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
regex = "1.5"
clap = "2.33.0"
itertools = "0.10"
num_cpus = "1.0"
flate2 = "1"
